port=0
interface=eth0                     # change to your real LAN NIC if needed
bind-interfaces
dhcp-range=10.200.1.100,10.200.1.200,12h
dhcp-option=3,10.200.1.1          # gateway
dhcp-option=6,10.200.1.1          # DNS
enable-tftp
tftp-root=/tftpboot
dhcp-boot=archlinux.efi
log-queries
log-dhcp
