name: Deploy PXE Server

on:
  workflow_dispatch:
    inputs:
      host:
        description: "Target PXE server (IP or hostname)"
        default: "pxe.rotko.net"
        required: true
      username:
        description: "SSH username"
        default: "pxe"
        required: true
      target_path:
        description: "Remote path to deploy"
        default: "~/pxe"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Sync to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ secrets.PXE_SSH_KEY }}
        source: "."
        target: ${{ inputs.target_path }}

    - name: Deploy containers
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ secrets.PXE_SSH_KEY }}
        script: |
          cd ${{ inputs.target_path }}
          docker compose down
          docker compose up -d --build
